import parse_json_store
import SCA_api
from SCA_api import nexus_server_url, nexus_username, nexus_password, SMTP_server, SMTP_port, SMTP_tls, SMTP_user, SMTP_password, Email_from
import requests
import os
import zipfile
import argparse
import time
import pandas as pd
from packaging.version import parse as version_parse
import urllib3
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# Disable SSL warnings for unverified HTTPS requests
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Configuration constants
NEXUS_REPOSITORY_SUFFIX = "/service/rest/v1/components?repository="
NEXUS_COMPONENTS_API = "/service/rest/v1/components"
CODE_FOLDER = 'manifest'
SCA_PROJECT_NAME = 'nexus_sca'

# Restricted licenses that should be flagged
RESTRICTED_LICENSES = [
    'GPL-2.0',
    'GPL-3.0',
    'AGPL-3.0',
    'LGPL-2.1',
    'LGPL-3.0',
    'SSPL-1.0',
    'OSL-3.0',
    'EPL-1.0',
    'EPL-2.0',
    'CDDL-1.0',
    'CDDL-1.1',
    'CPL-1.0',
    'IPL-1.0',
    'MPL-1.1',
    'MPL-2.0',
    'EUPL-1.1',
    'EUPL-1.2'
]

def send_email_report(recipients, subject, report_content, cvss_threshold=None, remove_packages=False, dry_run=True):
    """
    Send the vulnerability report via email.
    
    Args:
        recipients (list): List of recipient email addresses
        subject (str): Email subject
        report_content (str): The report content to send
        cvss_threshold (float): CVSS threshold used in the scan
        remove_packages (bool): Whether package removal was enabled
        dry_run (bool): Whether it was a dry run
        
    Returns:
        bool: True if email sent successfully, False otherwise
    """
    try:
        # Get email credentials if not configured
        smtp_server = SMTP_server
        smtp_port = SMTP_port
        use_tls = SMTP_tls
        from_email = Email_from
        
        # Create the email message
        msg = MIMEMultipart()
        msg['From'] = from_email
        msg['To'] = ', '.join(recipients)
        msg['Subject'] = subject
        
        # Create HTML email body
        html_body = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                .header {{ background-color: #f8f9fa; padding: 15px; border-left: 4px solid #007bff; }}
                .section {{ margin: 20px 0; }}
                .warning {{ background-color: #fff3cd; padding: 10px; border-left: 4px solid #ffc107; }}
                .success {{ background-color: #d4edda; padding: 10px; border-left: 4px solid #28a745; }}
                .error {{ background-color: #f8d7da; padding: 10px; border-left: 4px solid #dc3545; }}
                .vulnerability {{ background-color: #f8d7da; margin: 5px 0; padding: 8px; border-radius: 4px; }}
                .license-issue {{ background-color: #fff3cd; margin: 5px 0; padding: 8px; border-radius: 4px; }}
                .config-info {{ background-color: #e2e3e5; padding: 10px; border-radius: 4px; font-size: 0.9em; }}
                pre {{ background-color: #f8f9fa; padding: 15px; border-radius: 4px; overflow-x: auto; }}
                .timestamp {{ color: #6c757d; font-size: 0.9em; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Nexus SCA Vulnerability Scan Report</h1>
                <p class="timestamp">Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>
            
            <div class="section config-info">
                <h3>Scan Configuration</h3>
                <ul>
                    <li><strong>Nexus Server:</strong> {nexus_server_url}</li>
                    <li><strong>CVSS Threshold:</strong> {cvss_threshold if cvss_threshold else 'Not applied'}</li>
                    <li><strong>Package Removal:</strong> {'Enabled' if remove_packages else 'Disabled'}</li>
                    <li><strong>Execution Mode:</strong> {'Dry Run' if dry_run else 'Live Execution'}</li>
                </ul>
            </div>
            
            <div class="section">
                <h3>Report Details</h3>
                <pre>{report_content}</pre>
            </div>
            
            <div class="section">
                <p><em>This report was automatically generated by the Nexus SCA Scanner.</em></p>
            </div>
        </body>
        </html>
        """
        
        # Attach the HTML body
        msg.attach(MIMEText(html_body, 'html'))
        
        # Send the email
        print(f"Connecting to SMTP server: {smtp_server}:{smtp_port}")
        server = smtplib.SMTP(smtp_server, smtp_port)
        
        if use_tls:
            server.starttls()
        
        server.login(SMTP_user, SMTP_password)
        
        text = msg.as_string()
        server.sendmail(from_email, recipients, text)
        server.quit()
        
        print(f"✓ Email report sent successfully to: {', '.join(recipients)}")
        return True
        
    except Exception as e:
        print(f"✗ Failed to send email report: {e}")
        return False

def format_summary_report(all_vulnerabilities, all_license_issues, cvss_threshold=None, remove_packages=False, dry_run=True, processed_count=0):
    """
    Format the summary report for both console and email output.
    
    Args:
        all_vulnerabilities (list): List of vulnerabilities found
        all_license_issues (list): List of license issues found
        cvss_threshold (float): CVSS threshold used
        remove_packages (bool): Whether package removal was enabled
        dry_run (bool): Whether it was a dry run
        processed_count (int): Number of repositories processed
        
    Returns:
        str: Formatted report content
    """
    report_lines = []
    report_lines.append("=" * 80)
    report_lines.append("SUMMARY REPORT - PACKAGES TO REMOVE FROM ALL REPOSITORIES")
    if remove_packages and cvss_threshold:
        report_lines.append(f"(Filtered by CVSS threshold: {cvss_threshold})")
    if remove_packages:
        report_lines.append(f"(Execution mode: {'DRY RUN' if dry_run else 'LIVE EXECUTION'})")
    report_lines.append("=" * 80)
    
    if all_vulnerabilities:
        report_lines.append(f"\nTOTAL HIGH SEVERITY VULNERABILITIES: {len(all_vulnerabilities)}")
        for repo, (package, version, dep_type, risk_score, is_direct) in all_vulnerabilities:
            report_lines.append(f"  {repo}: {package} {version} {dep_type} (RiskScore: {risk_score})")
    
    if all_license_issues:
        report_lines.append(f"\nTOTAL RESTRICTED LICENSE ISSUES: {len(all_license_issues)}")
        for repo, (package, version, dep_type, risk_score, is_direct) in all_license_issues:
            report_lines.append(f"  {repo}: {package} {version} {dep_type} (RiskScore: {risk_score})")
    
    if not all_vulnerabilities and not all_license_issues:
        if remove_packages and cvss_threshold:
            report_lines.append(f"\nNo packages meet the CVSS threshold of {cvss_threshold} across all repositories.")
        else:
            report_lines.append("\nNo high severity vulnerabilities or license issues found across all repositories.")
    
    report_lines.append(f"\nProcessing complete. Processed {processed_count} repositories.")
    report_lines.append("=" * 80)
    
    return "\n".join(report_lines)

def get_nexus_proxy_repositories(nexus_url):
    """
    Retrieve list of proxy repositories from Nexus server.
    
    Args:
        nexus_url (str): The base URL of the Nexus server
        
    Returns:
        list: List of proxy repository names, empty list on error
    """
    url = f"{nexus_url}/service/rest/v1/repositories"
    try:
        response = requests.get(url, verify=False, timeout=30)
        response.raise_for_status()
        data = response.json()
        proxy_repositories = [repo["name"] for repo in data if repo["type"] == "proxy"]
        return proxy_repositories
    except requests.RequestException as e:
        print(f"Request error in get_nexus_proxy_repositories: {e}")
        return []
    except Exception as e:
        print(f"Exception in get_nexus_proxy_repositories: {e}")
        return []

def zip_file(source_file, zip_file_name):
    """
    Create a zip file containing the source file.
    
    Args:
        source_file (str): Path to the file to be zipped
        zip_file_name (str): Name of the output zip file
        
    Returns:
        bool: True if successful, False otherwise
    """
    try:
        if not os.path.exists(source_file):
            print(f"Source file does not exist: {source_file}")
            return False
            
        with zipfile.ZipFile(zip_file_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
            zipf.write(source_file, arcname=os.path.basename(source_file))
        return True
    except Exception as e:
        print(f"Exception in zip_file: {e}")
        return False

def treat_package_list(packages, format_type):
    """
    Process package list and create a zip file.
    
    Args:
        packages (dict): Dictionary of packages
        format_type (str): Package format type
        
    Returns:
        str: Path to zip file if successful, empty string otherwise
    """
    try:
        if not packages:
            print("No packages to process")
            return ""
            
        # Ensure manifest directory exists
        manifest_dir = os.path.join(os.getcwd(), CODE_FOLDER)
        os.makedirs(manifest_dir, exist_ok=True)
        
        file_name = str(parse_json_store.create_package(packages, manifest_dir, format_type))
        if not file_name or not os.path.exists(file_name):
            print("Failed to create package file")
            return ""
            
        zip_file_name = f"{file_name}.zip"
        
        if zip_file(file_name, zip_file_name):
            return zip_file_name
        else:
            return ""
            
    except Exception as e:
        print(f"Exception in treat_package_list: {e}")
        return ""

def get_nexus_component_id(repository_name, package_name, package_version, package_group=None):
    """
    Get the Nexus component ID for a specific package version.
    
    Args:
        repository_name (str): Name of the repository
        package_name (str): Name of the package
        package_version (str): Version of the package
        package_group (str): Group/namespace of the package (for Maven)
        
    Returns:
        str: Component ID if found, None otherwise
    """
    try:
        url = f"{nexus_server_url}{NEXUS_REPOSITORY_SUFFIX}{repository_name}"
        continuation_token = ''
        
        while continuation_token is not None:
            try:
                if continuation_token == '':
                    response = requests.get(url, auth=(nexus_username, nexus_password), verify=False, timeout=30)
                else:
                    response = requests.get(
                        f"{url}&continuationToken={continuation_token}", 
                        auth=(nexus_username, nexus_password),
                        verify=False, 
                        timeout=30
                    )
                
                response.raise_for_status()
                data = response.json()
                packages = data.get('items', [])
                
                if not packages:
                    break
                    
                continuation_token = data.get('continuationToken')
                
                for package in packages:
                    pkg_name = package.get('name', '')
                    pkg_version = package.get('version', '')
                    pkg_group = package.get('group', '')
                    pkg_id = package.get('id', '')
                    
                    # Match package based on format
                    if package_group:  # Maven format
                        if pkg_name == package_name and pkg_version == package_version and pkg_group == package_group:
                            return pkg_id
                    else:  # NPM, PyPI, etc.
                        if pkg_name == package_name and pkg_version == package_version:
                            return pkg_id
                            
            except requests.RequestException as e:
                print(f"Request error while searching for component: {e}")
                break
            except Exception as e:
                print(f"Error processing component search: {e}")
                break
                
        return None
        
    except Exception as e:
        print(f"Exception in get_nexus_component_id: {e}")
        return None

def delete_nexus_component(component_id):
    """
    Delete a component from Nexus repository by its ID.
    
    Args:
        component_id (str): The component ID to delete
        
    Returns:
        bool: True if successful, False otherwise
    """
    try:
        url = f"{nexus_server_url}{NEXUS_COMPONENTS_API}/{component_id}"
        
        response = requests.delete(url, auth=(nexus_username, nexus_password), verify=False, timeout=30)
        response.raise_for_status()
        
        print(f"Successfully deleted component ID: {component_id}")
        return True
        
    except requests.RequestException as e:
        print(f"Failed to delete component {component_id}: {e}")
        return False
    except Exception as e:
        print(f"Exception deleting component {component_id}: {e}")
        return False

def parse_package_info(package_name, package_version, dependency_value):
    """
    Parse package information to extract group/namespace information.
    
    Args:
        package_name (str): Package name
        package_version (str): Package version
        dependency_value (str): Dependency value that might contain group info
        
    Returns:
        tuple: (name, version, group) where group can be None
    """
    try:
        # For Maven packages, dependency_value format is "version|group"
        if '|' in dependency_value:
            version, group = dependency_value.split('|', 1)
            return package_name, version, group
        else:
            # For NPM, PyPI, etc., no group information
            return package_name, package_version, None
    except Exception as e:
        print(f"Error parsing package info: {e}")
        return package_name, package_version, None

def remove_packages_from_nexus(repository_name, packages_to_remove, dry_run=True):
    """
    Remove packages from Nexus repository based on vulnerability scan results.
    
    Args:
        repository_name (str): Name of the repository
        packages_to_remove (list): List of tuples (package_name, package_version, dep_type, risk_score, is_direct)
        dry_run (bool): If True, only simulate removal without actually deleting
        
    Returns:
        dict: Results of removal operations
    """
    results = {
        'attempted': 0,
        'successful': 0,
        'failed': 0,
        'not_found': 0,
        'details': []
    }
    
    print(f"\n{'='*60}")
    print(f"{'DRY RUN - ' if dry_run else ''}REMOVING PACKAGES FROM NEXUS REPOSITORY: {repository_name}")
    print(f"{'='*60}")
    
    for package_name, package_version, dep_type, risk_score, is_direct in packages_to_remove:
        results['attempted'] += 1
        
        try:
            # Parse package information
            name, version, group = parse_package_info(package_name, package_version, package_version)
            
            # Get component ID from Nexus
            component_id = get_nexus_component_id(repository_name, name, version, group)
            
            if component_id:
                if dry_run:
                    print(f"DRY RUN: Would delete {package_name} {package_version} {dep_type} (Component ID: {component_id})")
                    results['successful'] += 1
                else:
                    # Actually delete the component
                    if delete_nexus_component(component_id):
                        print(f"DELETED: {package_name} {package_version} {dep_type} (Component ID: {component_id})")
                        results['successful'] += 1
                        results['details'].append({
                            'package': package_name,
                            'version': package_version,
                            'action': 'deleted',
                            'component_id': component_id
                        })
                    else:
                        print(f"FAILED: Could not delete {package_name} {package_version} {dep_type}")
                        results['failed'] += 1
                        results['details'].append({
                            'package': package_name,
                            'version': package_version,
                            'action': 'failed',
                            'component_id': component_id
                        })
            else:
                print(f"NOT FOUND: {package_name} {package_version} {dep_type} (Component not found in Nexus)")
                results['not_found'] += 1
                results['details'].append({
                    'package': package_name,
                    'version': package_version,
                    'action': 'not_found',
                    'component_id': None
                })
                
        except Exception as e:
            print(f"ERROR: Processing {package_name} {package_version}: {e}")
            results['failed'] += 1
            results['details'].append({
                'package': package_name,
                'version': package_version,
                'action': 'error',
                'error': str(e)
            })
    
    # Print summary
    print(f"\n{'='*60}")
    print(f"REMOVAL SUMMARY FOR {repository_name}:")
    print(f"  Attempted: {results['attempted']}")
    print(f"  Successful: {results['successful']}")
    print(f"  Failed: {results['failed']}")
    print(f"  Not Found: {results['not_found']}")
    print(f"{'='*60}")
    
    return results

def filter_packages_by_cvss(vulnerabilities, license_issues, cvss_threshold=7.0):
    """
    Filter packages based on CVSS threshold.
    
    Args:
        vulnerabilities (list): List of vulnerability tuples
        license_issues (list): List of license issue tuples
        cvss_threshold (float): CVSS threshold (0-10)
        
    Returns:
        tuple: (filtered_vulnerabilities, filtered_license_issues)
    """
    filtered_vulnerabilities = []
    filtered_license_issues = []
    
    print(f"\nFiltering packages with CVSS threshold: {cvss_threshold}")
    
    for package_name, package_version, dep_type, risk_score, is_direct in vulnerabilities:
        try:
            # Try to parse risk_score as float for CVSS comparison
            if risk_score != 'N/A' and risk_score and str(risk_score).strip():
                try:
                    score = float(str(risk_score).strip())
                    if score >= cvss_threshold:
                        filtered_vulnerabilities.append((package_name, package_version, dep_type, risk_score, is_direct))
                        print(f"  INCLUDED: {package_name} {package_version} (CVSS: {score} >= {cvss_threshold})")
                    else:
                        print(f"  EXCLUDED: {package_name} {package_version} (CVSS: {score} < {cvss_threshold})")
                except (ValueError, TypeError) as e:
                    # If risk_score cannot be parsed as float, exclude it with CVSS threshold
                    print(f"  EXCLUDED: {package_name} {package_version} (Invalid CVSS score: '{risk_score}', error: {e})")
            else:
                # If no CVSS score available, exclude it when using CVSS threshold filtering
                print(f"  EXCLUDED: {package_name} {package_version} (No CVSS score available)")
                
        except Exception as e:
            print(f"  EXCLUDED: {package_name} {package_version} (Error processing CVSS: {e})")
    
    # For license issues, we include all since they're not CVSS-based
    filtered_license_issues = license_issues
    if license_issues:
        print(f"  Including all {len(license_issues)} license issues (not CVSS-based)")
    
    print(f"\nFiltering results:")
    print(f"  Original vulnerabilities: {len(vulnerabilities)}")
    print(f"  Filtered vulnerabilities (CVSS >= {cvss_threshold}): {len(filtered_vulnerabilities)}")
    print(f"  License issues: {len(filtered_license_issues)}")
    
    return filtered_vulnerabilities, filtered_license_issues

def get_packages_list(repository_name):
    """
    Retrieve packages from a Nexus repository.
    
    Args:
        repository_name (str): Name of the repository
        
    Returns:
        tuple: (dependencies dict, format string) or (None, None) on error
    """
    try:
        url = nexus_server_url + NEXUS_REPOSITORY_SUFFIX
        continuation_token = ''
        dependencies = {}
        file_format = ''

        print(f"\n{repository_name} packages:")

        while continuation_token is not None:
            try:
                if continuation_token == '':
                    response = requests.get(f"{url}{repository_name}", verify=False, timeout=30)
                else:
                    response = requests.get(
                        f"{url}{repository_name}&continuationToken={continuation_token}", 
                        verify=False, 
                        timeout=30
                    )
                
                response.raise_for_status()
                data = response.json()
                packages = data.get('items', [])
                
                if not packages:
                    break
                
                # Get format from first package if not already set
                if not file_format and packages:
                    file_format = packages[0].get('format', '')
                
                continuation_token = data.get('continuationToken')

                for package in packages:
                    package_name = package.get('name', '')
                    package_version = package.get('version', '')
                    package_group = package.get('group', '')
                    
                    if not package_name or not package_version:
                        continue
                        
                    print(f"{package_name} {package_version}")
                    
                    # Handle different package formats
                    if file_format == 'maven2':
                        dependency_key = package_name
                        dependency_value = f"{package_version}|{package_group}" if package_group else package_version
                    elif file_format == 'npm':
                        if package_group:
                            dependency_key = f"@{package_group}/{package_name}"
                        else:
                            dependency_key = package_name
                        dependency_value = package_version
                    else:
                        dependency_key = package_name
                        dependency_value = package_version
                    
                    # Check if package already exists and update with older version for scanning
                    if dependency_key in dependencies:
                        existing_version = dependencies[dependency_key].split('|')[0] if '|' in dependencies[dependency_key] else dependencies[dependency_key]
                        try:
                            # Keep the older version for vulnerability scanning (older versions more likely to have vulnerabilities)
                            if version_parse(package_version) < version_parse(existing_version):
                                dependencies[dependency_key] = dependency_value
                                print(f"  Updated {dependency_key}: {existing_version} -> {package_version} (using older version)")
                            # If current version is newer or equal, keep the existing older one
                        except Exception as version_error:
                            print(f"Version comparison error for {dependency_key}: {version_error}")
                            # If version comparison fails, keep the existing one (first encountered)
                            pass
                    else:
                        dependencies[dependency_key] = dependency_value
                        
            except requests.RequestException as e:
                print(f"Request error while fetching packages: {e}")
                break
            except Exception as e:
                print(f"Error processing packages batch: {e}")
                break

        return dependencies, file_format

    except Exception as e:
        print(f"Exception in get_packages_list: {e}")
        return None, None

def upload_offline_files():
    """
    Upload offline manifest files for SCA scanning.
    """
    try:
        manifest_dir = os.path.join(os.getcwd(), CODE_FOLDER)
        
        if not os.path.isdir(manifest_dir):
            print(f"The directory '{manifest_dir}' does not exist.")
            return

        # Iterate through all files in the 'manifest' directory
        for foldername, subfolders, filenames in os.walk(manifest_dir):
            for filename in filenames:
                if filename.endswith('.zip'):
                    try:
                        # Determine repository type based on filename
                        repository = 'repo'  # default
                        if 'package.json' in filename:
                            repository = 'npm'
                        elif 'nuget.csproj' in filename:
                            repository = 'nuget'
                        elif 'requirements.txt' in filename:
                            repository = 'pypi'
                        elif 'pom.xml' in filename:
                            repository = 'maven'
                        
                        # If zip file is generated, proceed with scanning
                        zip_full_path = os.path.join(foldername, filename)
                        project_name = f"{SCA_PROJECT_NAME}_{repository}"
                        
                        print(f"Uploading {filename} as project {project_name}")
                        SCA_scan_packages(project_name, zip_full_path)
                        
                    except Exception as e:
                        print(f"Error processing file {filename}: {e}")
                        
    except Exception as e:
        print(f"Exception in upload_offline_files: {e}")

def SCA_scan_packages(project_name, zip_manifest_file, access_token="", team_name=None, wait_for_report=False, remove_packages=False, cvss_threshold=7.0, dry_run=True):
    try:
        if(not access_token):
            access_token = SCA_api.get_access_token()

        project_id = SCA_api.SCA_get_project_id(project_name, access_token)
        if (project_id == ''):
            project_id = SCA_api.SCA_create_project(project_name, access_token, team_name)
        if (project_id == ''):
            return None
        upload_file_url = SCA_api.SCA_get_upload_link(project_id, access_token)
        if upload_file_url:
            SCA_api.SCA_upload_file(upload_file_url, zip_manifest_file, access_token)
            scan_id = SCA_api.SCA_scan_zip(project_id, upload_file_url, access_token)

            if wait_for_report and scan_id:
                status = 'Running'
                max_retries = 120  # 10 minutes with 5-second intervals
                retries = 0

                print(f"Waiting for scan to complete for project: {project_name}")
                while status == 'Running' and retries < max_retries:
                    time.sleep(5)
                    retries += 1
                    status = SCA_api.SCA_get_scan_status(scan_id, access_token)
                    print(f'Scan status: {status} (attempt {retries}/{max_retries})')

                if retries >= max_retries and status == 'Running':
                    print("Scan timed out after 10 minutes")
                    return None

                if status == 'Completed':
                    print(f"Scan completed for project: {project_name}")
                    try: 
                        vulnerabilities, license_issues = get_vulnerable_packages_from_report(project_name, access_token)
                        
                        # FIXED: Apply CVSS filtering when remove_packages is enabled
                        if remove_packages and cvss_threshold > 0:
                            print(f"\nApplying CVSS filtering with threshold: {cvss_threshold}")
                            vulnerabilities, license_issues = filter_packages_by_cvss(
                                vulnerabilities, license_issues, cvss_threshold
                            )
                        
                        issues_found = len(vulnerabilities) > 0 or len(license_issues) > 0
                        
                        if issues_found:
                            print(f"\n{'='*60}")
                            print(f"PACKAGES TO REMOVE FROM NEXUS REPOSITORY")
                            print(f"{'='*60}")
                            
                            if vulnerabilities:
                                print(f"\nHIGH SEVERITY VULNERABILITIES:")
                                print(f"Repository: {project_name.replace(SCA_PROJECT_NAME + '_', '')}")
                                for package, version, dep_type, risk_score, is_direct in vulnerabilities:
                                    print(f"  REMOVE: {package} {version} {dep_type} (RiskScore: {risk_score})")
                            
                            if license_issues:
                                print(f"\nRESTRICTED LICENSE ISSUES:")
                                print(f"Repository: {project_name.replace(SCA_PROJECT_NAME + '_', '')}")
                                for package, version, dep_type, risk_score, is_direct in license_issues:
                                    print(f"  REMOVE: {package} {version} {dep_type} (RiskScore: {risk_score})")
                            
                            print(f"\n{'='*60}")
                            
                            # Actually perform removal if requested
                            if remove_packages:
                                repository_name = project_name.replace(SCA_PROJECT_NAME + '_', '')
                                all_packages_to_remove = vulnerabilities + license_issues
                                print(f"DEBUG: remove_packages={remove_packages}, packages_to_remove={len(all_packages_to_remove)}")
                                
                                if all_packages_to_remove:
                                    print(f"EXECUTING REMOVAL: Calling remove_packages_from_nexus for {repository_name}")
                                    print(f"DEBUG: About to call remove_packages_from_nexus with {len(all_packages_to_remove)} packages")
                                    
                                    # THIS IS THE ACTUAL FUNCTION CALL THAT WAS MISSING
                                    removal_results = remove_packages_from_nexus(
                                        repository_name, 
                                        all_packages_to_remove, 
                                        dry_run=dry_run
                                    )
                                    
                                    print(f"Removal operation completed for {repository_name}:")
                                    print(f"  Attempted: {removal_results['attempted']}")
                                    print(f"  Successful: {removal_results['successful']}")
                                    print(f"  Failed: {removal_results['failed']}")
                                    print(f"  Not Found: {removal_results['not_found']}")
                                else:
                                    print(f"No packages to remove for {repository_name}")
                            
                        else:
                            if remove_packages and cvss_threshold > 0:
                                print(f"No packages meet the CVSS threshold of {cvss_threshold} for project '{project_name}'.")
                            else:
                                print(f"No high severity vulnerabilities or license issues found for project '{project_name}'.")
                            
                        return vulnerabilities, license_issues
                        
                    except Exception as report_error:
                        print(f"Error processing vulnerability report: {report_error}")
                        return None
                else:
                    print(f"Scan finished with status: {status}")
                    return None
            else:
                print(f"Scan initiated for project: {project_name}. Use --wait-report to wait for completion.")
                return None
                
    except Exception as e:
        print("Exception: SCA_scan_packages failed:", str(e))
        return None

def get_vulnerable_packages_from_report(project_name, access_token=""):
    try:
        if not access_token:
            access_token = SCA_api.get_access_token()

        SCA_report_path = SCA_api.SCA_get_report(project_name, 'csv', access_token)
        if not SCA_report_path:
            print(f"No SCA report found for project: {project_name}")
            return [], []

        # Step 4: Extract and process the CSV files from the zip
        csv_filename = 'Packages.csv'
        extracted_data = {}

        try:
            with zipfile.ZipFile(SCA_report_path, 'r') as zip_ref:
                with zip_ref.open(csv_filename) as csv_file:
                    extracted_data[csv_filename] = pd.read_csv(csv_file)

            # Process Packages.csv if it was successfully extracted
            if csv_filename in extracted_data:
                packages_df = extracted_data[csv_filename]

                # Ensure necessary columns exist before filtering
                required_columns = {'Severity', 'IsDirectDependency', 'Licenses'}
                if not required_columns.issubset(packages_df.columns):
                    print("Warning: Required columns not found in CSV")
                    return [], []

                # Convert columns to strings (avoid NaN type issues)
                packages_df['Severity'] = packages_df['Severity'].astype(str).str.lower()
                packages_df['Licenses'] = packages_df['Licenses'].astype(str)
                
                # Check if RiskScore column exists and handle it
                has_risk_score = 'RiskScore' in packages_df.columns
                if has_risk_score:
                    packages_df['RiskScore'] = packages_df['RiskScore'].fillna('N/A')  # Handle NaN values
                    print("RiskScore column found and will be included in results")
                else:
                    print("RiskScore column not found in CSV - will use 'N/A' as default")

                # Separate high-severity vulnerabilities and license issues
                vulnerabilities = []
                license_issues = []

                for _, row in packages_df.iterrows():
                    package_name = row['Name']
                    package_version = row['Version']
                    is_direct = row['IsDirectDependency']  # This is the boolean value we need
                    dependency_type = "(direct)" if is_direct else "(transitive)"
                    risk_score = row['RiskScore'] if has_risk_score else 'N/A'
                    
                    # Check if package is listed due to a restricted license
                    found_due_to_license = [
                        license for license in RESTRICTED_LICENSES if license in row['Licenses']
                    ]

                    # Classify package into the correct list - NOW INCLUDING is_direct boolean
                    if row['Severity'] == 'high':
                        vulnerabilities.append((package_name, package_version, dependency_type, risk_score, is_direct))
                    if found_due_to_license:
                        license_text = f" - Found due to {', '.join(found_due_to_license)} license"
                        license_issues.append((package_name, package_version, dependency_type + license_text, risk_score, is_direct))

                # Print vulnerabilities
                if vulnerabilities:
                    print(f"\nHigh Severity Vulnerable Packages in '{project_name}':")
                    for package, version, dep_type, risk_score, _ in vulnerabilities:  # Note: added _ for is_direct
                        print(f"- {package} {version} {dep_type} (RiskScore: {risk_score})")
                else:
                    print(f"No high severity packages found for project '{project_name}'.")

                # Print license issues
                if license_issues:
                    print(f"\nRestricted License Packages in '{project_name}':")
                    for package, version, dep_type, risk_score, _ in license_issues:  # Note: added _ for is_direct
                        print(f"- {package} {version} {dep_type} (RiskScore: {risk_score})")
                else:
                    print(f"No restricted license packages found for project '{project_name}'.")

                return vulnerabilities, license_issues

        except Exception as project_error:
            print(f"Error processing project '{project_name}': {project_error}")
            return [], []

        finally:
            # Delete the zip file after processing
            if os.path.exists(SCA_report_path):
                os.remove(SCA_report_path)

    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return [], []

def main():
    """
    Main function to orchestrate the Nexus SCA scanning process.
    """
    # Create the parser
    parser = argparse.ArgumentParser(
        description="Nexus SCA Package Scanner - Scan Nexus repositories for security vulnerabilities"
    )
    
    # Add the arguments
    parser.add_argument(
        '--repo', 
        type=str, 
        help='Limit scanning to a specific repository name'
    )
    
    parser.add_argument(
        '--offline', 
        action='store_true', 
        help='Run in offline mode (generate manifest files without uploading to SCA)'
    )
    
    parser.add_argument(
        '--upload', 
        action='store_true', 
        help='Upload existing manifest zip files from the manifest folder to SCA'
    )
    
    parser.add_argument(
        '--wait-report', 
        action='store_true', 
        help='Wait for vulnerability report completion and list high severity and license issues for removal'
    )
    
    parser.add_argument(
        '--remove-packages', 
        action='store_true', 
        help='Remove vulnerable packages from Nexus repositories (use with --cvss-threshold)'
    )
    
    parser.add_argument(
        '--cvss-threshold', 
        type=float,
        default=7.0,
        help='CVSS threshold for package removal (default: 7.0, range: 0-10)'
    )
    
    parser.add_argument(
        '--dry-run', 
        action='store_true',
        default=True,
        help='Perform a dry run without actually removing packages (default: True)'
    )
    
    parser.add_argument(
        '--force-remove', 
        action='store_true',
        help='Actually remove packages from Nexus (disables dry-run mode)'
    )
    
    parser.add_argument(
        '--email-recipients', 
        type=str, 
        nargs='+',
        help='Email addresses to send the vulnerability report to (space-separated)'
    )
    
    parser.add_argument(
        '--email-subject', 
        type=str,
        default='Nexus SCA Vulnerability Report',
        help='Subject line for the email report (default: "Nexus SCA Vulnerability Report")'
    )
    
    # Parse the arguments
    args = parser.parse_args()
    
    # Extract arguments with defaults
    limit_repo = args.repo or ""
    offline = args.offline
    upload = args.upload
    wait_report = args.wait_report
    remove_packages = args.remove_packages
    cvss_threshold = args.cvss_threshold
    dry_run = args.dry_run and not args.force_remove  # Disable dry-run if force-remove is set
    email_recipients = args.email_recipients or []
    email_subject = args.email_subject
    
    # Validate CVSS threshold
    if cvss_threshold < 0 or cvss_threshold > 10:
        print("Error: CVSS threshold must be between 0 and 10")
        return
    
    # Validate remove packages requires wait report
    if remove_packages and not wait_report:
        print("Error: --remove-packages requires --wait-report")
        return
    
    print(f"Configuration:")
    print(f"  Limit repo: {limit_repo if limit_repo else 'None (all repos)'}")
    print(f"  Offline mode: {offline}")
    print(f"  Upload mode: {upload}")
    print(f"  Wait for report: {wait_report}")
    print(f"  Remove packages: {remove_packages}")
    print(f"  CVSS threshold: {cvss_threshold}")
    print(f"  Dry run mode: {dry_run}")
    print(f"  Email recipients: {email_recipients if email_recipients else 'None'}")
    print(f"  Nexus server: {nexus_server_url}")
    
    if remove_packages:
        print(f"\n{'='*60}")
        print(f"WARNING: Package removal is {'ENABLED' if not dry_run else 'ENABLED (DRY RUN)'}")
        print(f"CVSS Threshold: {cvss_threshold}")
        print(f"Nexus Credentials: {nexus_username}@{nexus_server_url}")
        print(f"{'='*60}")
        
    try:
        if upload:
            upload_offline_files()
        else:    
            # 1. Get the list of Nexus proxy repositories
            proxy_repositories = get_nexus_proxy_repositories(nexus_server_url)
            
            if not proxy_repositories:
                print("No proxy repositories found or error occurred.")
                return

            # Print the list of proxy repositories
            print(f"\nFound {len(proxy_repositories)} proxy repositories:")
            for repository in proxy_repositories:
                print(f"  - {repository}")

            # Iterate through each repository
            processed_count = 0
            all_vulnerabilities = []
            all_license_issues = []
            
            for repository in proxy_repositories:
                # Check if limit_repo is empty or matches the current repository
                if not limit_repo or repository == limit_repo:
                    print(f"\nProcessing repository: {repository}")
                    
                    # Get the list of packages for the current repository
                    packages_list, format_type = get_packages_list(repository)
                    
                    if packages_list is None:
                        print(f"Failed to retrieve packages for repository: {repository}")
                        continue
                    
                    if not packages_list:
                        print(f"No packages found in repository: {repository}")
                        continue
                    
                    print(f"Found {len(packages_list)} packages in {repository}")
                    
                    # Treat the package list to create a zip file
                    zip_file_name = treat_package_list(packages_list, format_type)
                    
                    if zip_file_name:
                        print(f"Created manifest file: {zip_file_name}")
                        
                        # If zip file is generated and not in offline mode, proceed with scanning
                        if not offline:
                            project_name = f"{SCA_PROJECT_NAME}_{repository}"
                            print(f"Uploading to SCA as project: {project_name}")
                            print(f"DEBUG: Calling SCA_scan_packages with remove_packages={remove_packages}, cvss_threshold={cvss_threshold}")
                            result = SCA_scan_packages(
                                project_name, 
                                zip_file_name, 
                                wait_for_report=wait_report,
                                remove_packages=remove_packages,
                                cvss_threshold=cvss_threshold,
                                dry_run=dry_run
                            )
                            
                            print(f"DEBUG: SCA_scan_packages returned: {result is not None}")
                            
                            if wait_report and result:
                                vulnerabilities, license_issues = result
                                all_vulnerabilities.extend([(repository, v) for v in vulnerabilities])
                                all_license_issues.extend([(repository, l) for l in license_issues])
                                
                                # Additional removal logic at repository level if needed
                                if remove_packages and not offline:
                                    print(f"DEBUG: Repository-level removal check for {repository}")
                                    if vulnerabilities or license_issues:
                                        print(f"Found {len(vulnerabilities)} vulnerabilities and {len(license_issues)} license issues for {repository}")
                                    else:
                                        print(f"No issues found for {repository} - nothing to remove")
                        else:
                            print("Offline mode: Skipping SCA upload")
                    else:
                        print(f"Failed to create manifest file for repository: {repository}")
                    
                    processed_count += 1
            
            # Summary report if waiting for reports
            if wait_report and not offline:
                # Generate the formatted report
                summary_report = format_summary_report(
                    all_vulnerabilities, 
                    all_license_issues, 
                    cvss_threshold, 
                    remove_packages, 
                    dry_run, 
                    processed_count
                )
                
                # Print to console
                print(summary_report)
                
                # Send email if recipients are specified
                if email_recipients:
                    print(f"\n{'='*60}")
                    print(f"SENDING EMAIL REPORT")
                    print(f"{'='*60}")
                    
                    # Create email subject with timestamp and summary
                    total_issues = len(all_vulnerabilities) + len(all_license_issues)
                    enhanced_subject = f"{email_subject} - {total_issues} Issues Found ({datetime.now().strftime('%Y-%m-%d %H:%M')})"
                    
                    # Send the email
                    email_sent = send_email_report(
                        recipients=email_recipients,
                        subject=enhanced_subject,
                        report_content=summary_report,
                        cvss_threshold=cvss_threshold,
                        remove_packages=remove_packages,
                        dry_run=dry_run
                    )
                    
                    if email_sent:
                        print(f"✓ Report successfully sent to {len(email_recipients)} recipient(s)")
                    else:
                        print(f"✗ Failed to send email report")
                
            print(f"\nProcessing complete. Processed {processed_count} repositories.")
            
    except KeyboardInterrupt:
        print("\nOperation cancelled by user.")
    except Exception as e:
        print(f"Unexpected error in main: {e}")

if __name__ == '__main__':
    main()